all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /root/.ssh/ansiblekey
  children:
    LinuxServers:
      hosts:
        VM-WEB-V01:
          ansible_host: 192.168.0.71
          ansible_python_interpreter: /usr/bin/python3
          role: linux
          environment: production
        VM-BDD-V02:
          ansible_host: 192.168.0.72
          ansible_python_interpreter: /usr/bin/python3
          role: linux
          environment: production
        VM-ORA-V03:
          ansible_host: 192.168.0.73
          ansible_python_interpreter: /usr/bin/python3
          role: linux
          environment: production
        VM-ANS-V04:
          ansible_host: 192.168.0.74
          ansible_python_interpreter: /usr/bin/python3
          role: linux
          environment: production
        VM-NET-V05:
          ansible_host: 192.168.0.75
          ansible_python_interpreter: /usr/bin/python3
          role: linux
          environment: production
        VM-ZBX-V06:
          ansible_host: 192.168.0.76
          ansible_python_interpreter: /usr/bin/python3
          role: linux
          environment: production

